# Spring Datasource (PostgreSQL)
spring.datasource.url=jdbc:postgresql://147.93.86.60:5432/mutualtm
spring.datasource.username=moonseptm
spring.datasource.password=dj^38Jek_d,@g$hd
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Security / JWT
mutualt.app.jwtSecret=MoonSeptMutualTransferSecretKeyForJwtAuthenticationMustBeAtLeast64CharactersLongForHS512Compliance!
mutualt.app.jwtExpirationMs=604800000

# Server
server.port=8080

# Multipart File Uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
